#!/bin/bash
# Abre o diretório Downloads do usuário
cd /home/$USER/Downloads
pwd
ls
echo "Colocar a hash do arquivo"
read codigo;
echo "Coloque o nome do arquivo"
read arquivo;
hash1=$(echo "$codigo  $arquivo")
echo "$hash1"
hash2=`sha256sum "$arquivo"`
echo "$hash2"
test -n "$hash1"; echo $?
test -n "$hash2"; echo $?
if [ "$hash1" = "$hash2" ]; then
echo "SUCESSO"
else
 echo "FRACASSO"
fi
#Os comentários foram iniciados neste código em 08/11/2020, foram também corrigidos erros de gráfia
